version: '2'

services:
    web:
        build:
            context: .
            dockerfile: ./Dockerfile
            args:
                STATIC_URL: '/static/'
        restart: unless-stopped
        networks:
            - app-be
        depends_on:
            - db
    db:
        image: library/postgres:11.1-alpine
        restart: unless-stopped
        networks:
            - app-be
        volumes:
            - app-db:/var/lib/postgresql
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
volumes:
    app-db:
        driver: local
networks:
    app-be:
        driver: bridge


