# Generated by Django 2.1.7 on 2019-04-01 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='County Code')),
                ('name', models.CharField(max_length=21)),
            ],
        ),
        migrations.CreateModel(
            name='SubCounty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kenya.County')),
            ],
        ),
        migrations.AddField(
            model_name='constituency',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kenya.County'),
        ),
    ]
